<template>
  <div class="enterprise-page">
    <header class="page-title"><div><span>DATA GOVERNANCE</span><h1>数据质量中心</h1><p>持续检查主数据完整性、账号绑定和业务可追溯性，让统计结果经得起核对。</p></div><el-button type="primary" @click="load"><el-icon><Refresh /></el-icon>重新扫描</el-button></header>
    <section class="score-panel"><div class="score-ring" :style="{ '--score': score * 3.6 + 'deg' }"><div><strong>{{ score }}</strong><span>质量分</span></div></div><div class="score-copy"><span :class="score>=90?'healthy':'warning'">{{score>=90?'数据健康':'需要治理'}}</span><h2>{{ issues.length ? `发现 ${issues.length} 类待处理问题` : '关键数据检查全部通过' }}</h2><p>评分覆盖药品主数据完整性、账号绑定关系和业务凭证三个维度。</p></div></section>
    <section class="quality-grid"><article><span><el-icon><Collection /></el-icon></span><div><small>药品主数据</small><strong>{{ medicineSummary.total_count || 0 }}</strong><em>{{ medicineSummary.incomplete_count || 0 }} 条待完善</em></div></article><article><span><el-icon><UserFilled /></el-icon></span><div><small>安心用药成员</small><strong>{{ elders.length }}</strong><em>{{ unboundElders.length }} 人未绑定家属</em></div></article><article><span><el-icon><CircleCheckFilled /></el-icon></span><div><small>启用档案占比</small><strong>{{ activeRate }}%</strong><em>业务可用性</em></div></article></section>
    <el-card shadow="never" class="issue-card"><template #header><div class="card-head"><b>治理任务清单</b><span>按影响程度排序</span></div></template><div v-for="item in issues" :key="item.code" class="issue-row"><span class="issue-icon" :class="item.level"><el-icon><component :is="item.icon"/></el-icon></span><div><b>{{item.title}}</b><p>{{item.description}}</p></div><el-tag :type="item.level==='high'?'danger':'warning'">{{item.count}} 条</el-tag><el-button plain size="small" @click="$router.push(item.path)">去处理</el-button></div><el-result v-if="!issues.length" icon="success" title="数据状态良好" sub-title="当前没有发现影响业务的关键数据问题"/></el-card>
  </div>
</template>
<script setup>
import { computed,onMounted,ref } from 'vue'; import { getMedicineOverview } from '../../api/medicine'; import { getUserList } from '../../api/user';
const medicineSummary=ref({}),elders=ref([]);const unboundElders=computed(()=>elders.value.filter(i=>!i.bindParentId));const activeRate=computed(()=>{const total=Number(medicineSummary.value.total_count||0);return total?Math.round(Number(medicineSummary.value.active_count||0)/total*100):100});const issues=computed(()=>{const list=[];const incomplete=Number(medicineSummary.value.incomplete_count||0);if(incomplete)list.push({code:'medicine',level:'high',icon:'FirstAidKit',title:'药品主数据不完整',description:'缺少图片、生产企业或价格基准会影响申请估价和收货核验。',count:incomplete,path:'/medicine'});if(unboundElders.value.length)list.push({code:'binding',level:'high',icon:'Link',title:'家庭成员尚未建立绑定关系',description:'未绑定家属将无法发送购药申请、消息和收货异常提醒。',count:unboundElders.value.length,path:'/system'});const disabled=Number(medicineSummary.value.disabled_count||0);if(disabled)list.push({code:'disabled',level:'medium',icon:'RemoveFilled',title:'存在已停用药品档案',description:'请确认停用药品是否仍被在用方案引用，避免新增业务选择错误。',count:disabled,path:'/medicine'});return list});const score=computed(()=>Math.max(0,100-Math.min(40,issues.value.reduce((s,i)=>s+i.count*(i.level==='high'?3:1),0))));const load=async()=>{const [m,u]=await Promise.all([getMedicineOverview(),getUserList('ELDER')]);medicineSummary.value=m.data||{};elders.value=u.data||[]};onMounted(load)
</script>
<style scoped>
.enterprise-page{max-width:1400px;margin:auto}.page-title{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:20px}.page-title span{color:#0b8f73;font-size:10px;font-weight:800;letter-spacing:2px}.page-title h1{margin:7px 0 5px;color:#13343d;font-size:27px}.page-title p{margin:0;color:#768a90;font-size:13px}.score-panel{display:flex;align-items:center;gap:24px;padding:22px;margin-bottom:14px;border:1px solid #e3eaeb;border-radius:16px;background:linear-gradient(135deg,#fff,#f3faf8)}.score-ring{width:104px;height:104px;display:grid;place-items:center;border-radius:50%;background:conic-gradient(#13aa7c var(--score),#e5edeb 0)}.score-ring>div{width:82px;height:82px;display:grid;place-items:center;align-content:center;border-radius:50%;background:#fff}.score-ring strong,.score-ring span{display:block}.score-ring strong{font-size:28px;color:#164139}.score-ring span{color:#80938e;font-size:10px}.score-copy>span{padding:4px 8px;border-radius:20px;font-size:10px}.score-copy>span.healthy{color:#0a896a;background:#e4f7ef}.score-copy>span.warning{color:#b26d18;background:#fff0d8}.score-copy h2{margin:9px 0 5px;color:#183b43}.score-copy p{margin:0;color:#7c8e92;font-size:12px}.quality-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:14px}.quality-grid article{display:flex;align-items:center;gap:13px;padding:17px;border:1px solid #e4eaec;border-radius:14px;background:#fff}.quality-grid article>span{width:42px;height:42px;display:grid;place-items:center;border-radius:12px;color:#0d8a70;background:#eaf7f3;font-size:20px}.quality-grid small,.quality-grid strong,.quality-grid em{display:block}.quality-grid small{color:#7d8d91;font-size:10px}.quality-grid strong{margin:3px 0;color:#173941;font-size:22px}.quality-grid em{color:#9aa7aa;font-size:10px;font-style:normal}.issue-card{border:1px solid #e4eaec;border-radius:16px}.card-head{display:flex;align-items:center;justify-content:space-between}.card-head span{color:#98a5a8;font-size:10px}.issue-row{display:grid;grid-template-columns:42px 1fr auto auto;align-items:center;gap:13px;padding:14px 0;border-bottom:1px solid #edf1f2}.issue-row:last-child{border-bottom:0}.issue-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:11px}.issue-icon.high{color:#c95543;background:#fbeae7}.issue-icon.medium{color:#b47518;background:#fff1dc}.issue-row b{color:#26474f;font-size:13px}.issue-row p{margin:4px 0 0;color:#87979b;font-size:11px}@media(max-width:760px){.page-title{align-items:flex-start;flex-direction:column;gap:12px}.quality-grid{grid-template-columns:1fr}.issue-row{grid-template-columns:38px 1fr auto}.issue-row>.el-tag{display:none}}
</style>
