<template>
  <div class="enterprise-page">
    <header class="page-title"><div><span>EVIDENCE ARCHIVE</span><h1>费用凭证档案</h1><p>把购药时间、平台、金额、批准文号和订单凭证整理成可追溯的低保与家庭对账资料。</p></div><el-button type="primary" @click="exportAll"><el-icon><Download /></el-icon>导出完整明细</el-button></header>
    <section class="metrics"><article><small>累计支出</small><strong>¥{{ money(summary.total_amount) }}</strong><span>{{ summary.order_count || 0 }} 笔购药业务</span></article><article><small>当前页有凭证</small><strong>{{ withProof }}</strong><span>截图或票据可追溯</span></article><article><small>当前页缺凭证</small><strong>{{ withoutProof }}</strong><span>建议及时补录</span></article><article><small>线上支出占比</small><strong>{{ onlineRatio }}%</strong><span>平台购药可核验</span></article></section>
    <el-card shadow="never" class="archive-card">
      <div class="toolbar"><el-input v-model="approvalNumber" :prefix-icon="Search" clearable placeholder="搜索国药准字号" @keyup.enter="load" @clear="load"/><el-select v-model="proofFilter" placeholder="凭证完整性" clearable><el-option label="凭证完整" value="complete"/><el-option label="缺少凭证" value="missing"/></el-select><el-button type="primary" plain @click="load">查询</el-button><span>共 {{ page.total }} 条记录</span></div>
      <el-table :data="filteredRecords" v-loading="loading">
        <el-table-column prop="purchaseDate" label="购药日期" width="115"/><el-table-column label="药品与成员" min-width="190"><template #default="{row}"><b>{{row.medicineName}}</b><small class="sub">{{row.userName}} · {{row.specification}}</small></template></el-table-column><el-table-column prop="approvalNumber" label="国药准字号" min-width="160"/><el-table-column label="渠道" width="130"><template #default="{row}">{{row.purchasePlatform||'未填写'}}<small class="sub">{{row.purchaseChannel==='OFFLINE'?'线下':'线上'}}</small></template></el-table-column><el-table-column label="金额" width="110" align="right"><template #default="{row}"><b class="amount">¥{{money(row.totalPrice)}}</b></template></el-table-column><el-table-column label="凭证状态" width="110" align="center"><template #default="{row}"><el-tag :type="row.proofUrl?'success':'warning'" effect="light">{{row.proofUrl?'已归档':'待补录'}}</el-tag></template></el-table-column><el-table-column label="业务状态" width="110" align="center"><template #default="{row}"><el-tag :type="row.receiptStatus===1?'success':'info'" effect="plain">{{row.receiptStatus===1?'已收货':'待核验'}}</el-tag></template></el-table-column>
      </el-table>
      <div class="pagination"><el-pagination v-model:current-page="page.current" v-model:page-size="page.size" :total="page.total" :page-sizes="[20,50,100]" layout="sizes, prev, pager, next" @size-change="load" @current-change="load"/></div>
    </el-card>
  </div>
</template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue'; import { Search } from '@element-plus/icons-vue'; import { getPurchasePage,getExpenseSummary } from '../../api/purchase'; import { downloadFile } from '../../utils/download'; import { ElMessage } from 'element-plus'
const records=ref([]),summary=ref({}),loading=ref(false),approvalNumber=ref(''),proofFilter=ref(''); const page=reactive({current:1,size:20,total:0}); const money=v=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}); const withProof=computed(()=>records.value.filter(i=>i.proofUrl).length); const withoutProof=computed(()=>records.value.length-withProof.value); const onlineRatio=computed(()=>{const total=Number(summary.value.total_amount||0);return total?Math.round(Number(summary.value.online_amount||0)/total*100):0}); const filteredRecords=computed(()=>proofFilter.value==='complete'?records.value.filter(i=>i.proofUrl):proofFilter.value==='missing'?records.value.filter(i=>!i.proofUrl):records.value)
const load=async()=>{loading.value=true;try{const [list,total]=await Promise.all([getPurchasePage({current:page.current,size:page.size,approvalNumber:approvalNumber.value}),getExpenseSummary()]);records.value=list.data.records||[];page.total=list.data.total||0;summary.value=total.data||{}}finally{loading.value=false}}; const exportAll=async()=>{await downloadFile('/export/purchase',{},'购药费用凭证明细.xlsx');ElMessage.success('费用凭证明细已导出')};onMounted(load)
</script>
<style scoped>
.enterprise-page{max-width:1500px;margin:auto}.page-title{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:20px}.page-title span{color:#0b8f73;font-size:10px;font-weight:800;letter-spacing:2px}.page-title h1{margin:7px 0 5px;color:#13343d;font-size:27px}.page-title p{margin:0;color:#768a90;font-size:13px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:16px}.metrics article{padding:18px;border:1px solid #e4eaec;border-radius:15px;background:#fff}.metrics small,.metrics strong,.metrics span{display:block}.metrics small{color:#7d8e92;font-size:11px}.metrics strong{margin:5px 0;color:#183a43;font-size:23px}.metrics span{color:#9ba8ab;font-size:10px}.archive-card{border:1px solid #e4eaec;border-radius:16px}.toolbar{display:flex;align-items:center;gap:9px;padding-bottom:15px;border-bottom:1px solid #edf1f2}.toolbar .el-input{max-width:280px}.toolbar .el-select{width:150px}.toolbar>span{margin-left:auto;color:#87979b;font-size:11px}.sub{display:block;margin-top:4px;color:#94a2a6;font-size:10px}.amount{color:#16745e}.pagination{display:flex;justify-content:flex-end;padding-top:15px}@media(max-width:760px){.page-title{align-items:flex-start;flex-direction:column;gap:12px}.metrics{grid-template-columns:1fr 1fr;gap:8px}.toolbar{flex-wrap:wrap}.toolbar .el-input{max-width:none}.toolbar>span{width:100%;margin:0}}
</style>
