<template>
  <div class="feature-page">
    <div class="page-heading"><div><p class="overline dark">SOFTWARE DELIVERY</p><h1>软件工程服务中心</h1><p>只提供合规的需求分析、开发辅导、代码实现、调试测试、部署运维与技术咨询。</p></div><el-button type="primary" size="large" @click="requestDialog=true">提交新需求</el-button></div>
    <section v-if="isAdmin" class="panel public-inquiry-panel"><div class="panel-head"><div><small>PUBLIC INQUIRIES</small><h3>游客咨询收件箱</h3></div><el-button text @click="loadPublicInquiries">刷新</el-button></div><div class="public-inquiry-grid"><article v-for="item in publicInquiries" :key="item.inquiryId" @click="openPublicInquiry(item.inquiryId)"><i :class="item.status.toLowerCase()">{{publicStatusNames[item.status]}}</i><h3>{{item.contactName}} · {{typeNames[item.serviceType]}}</h3><p>{{item.inquiryText}}</p><footer><span>{{item.inquiryNo}}</span><b>{{item.contactValue}}</b></footer></article></div><el-empty v-if="!publicInquiries.length" description="暂无游客咨询" :image-size="60" /></section>
    <section class="service-overview"><div><b>{{counts.all}}</b><small>全部需求</small></div><div><b>{{counts.progress}}</b><small>进行中</small></div><div><b>{{counts.delivered}}</b><small>已交付</small></div><p><strong>过程透明</strong><span>状态、报价、里程碑、问题工单均可追溯</span></p></section>
    <section class="panel"><div class="panel-head"><div><small>REQUEST PIPELINE</small><h3>需求看板</h3></div><el-select v-model="statusFilter" clearable placeholder="全部状态" @change="load"><el-option v-for="(v,k) in statusNames" :key="k" :label="v" :value="k" /></el-select></div>
      <div class="request-grid"><article v-for="r in requests" :key="r.requestId" @click="openDetail(r.requestId)"><div class="request-top"><span>{{typeNames[r.serviceType]||r.serviceType}}</span><i :class="`status-${r.status}`">{{statusNames[r.status]||r.status}}</i></div><h3>{{r.title}}</h3><p>{{r.requirementText}}</p><footer><small>{{r.createTime?.replace('T',' ')}}</small><b>查看详情 →</b></footer></article></div><el-empty v-if="!requests.length" description="暂无服务需求" />
    </section>
    <section class="compliance-note"><b>服务边界说明</b><p>平台不提供论文代写、考试作弊或伪造材料服务；所有交付强调学习指导、代码讲解、可运行测试与真实部署能力。</p></section>

    <el-dialog v-model="requestDialog" title="提交软件服务需求" width="min(680px,94vw)" class="stable-dialog"><el-form label-position="top"><div class="form-grid"><el-form-item label="服务类型"><el-select v-model="requestForm.serviceType" class="full"><el-option v-for="(v,k) in typeNames" :key="k" :label="v" :value="k" /></el-select></el-form-item><el-form-item label="期望日期"><el-date-picker v-model="requestForm.expectedDate" value-format="YYYY-MM-DD" class="full" /></el-form-item></div><el-form-item label="需求标题"><el-input v-model="requestForm.title" maxlength="120" show-word-limit /></el-form-item><el-form-item label="需求说明"><el-input v-model="requestForm.requirementText" type="textarea" :rows="5" maxlength="5000" show-word-limit /></el-form-item><div class="form-grid"><el-form-item label="技术栈"><el-input v-model="requestForm.technologyStack" placeholder="Spring Boot、Vue、MySQL…" /></el-form-item><el-form-item label="预算范围"><el-input v-model="requestForm.budgetRange" placeholder="例如：待评估" /></el-form-item></div><el-form-item label="联系方式"><el-input v-model="requestForm.contactChannel" placeholder="仅供本次需求沟通" /></el-form-item></el-form><template #footer><el-button @click="requestDialog=false">取消</el-button><el-button type="primary" @click="createRequest">提交评估</el-button></template></el-dialog>

    <el-drawer v-model="detailDrawer" :size="drawerSize" title="需求交付档案" class="detail-drawer">
      <template v-if="detail.request"><div class="detail-title"><span>{{typeNames[detail.request.serviceType]}}</span><h2>{{detail.request.title}}</h2><p>{{detail.request.requirementText}}</p></div><dl class="detail-meta"><div><dt>当前状态</dt><dd>{{statusNames[detail.request.status]}}</dd></div><div><dt>报价</dt><dd>{{detail.request.quoteAmount==null?'待评估':'¥'+detail.request.quoteAmount}}</dd></div><div><dt>期望日期</dt><dd>{{detail.request.expectedDate||'未填写'}}</dd></div><div><dt>技术栈</dt><dd>{{detail.request.technologyStack||'待沟通'}}</dd></div></dl>
        <section v-if="isAdmin" class="admin-action"><h3>管理员处理</h3><el-select v-model="statusForm.status" class="full"><el-option v-for="(v,k) in statusNames" :key="k" :label="v" :value="k" /></el-select><el-input-number v-model="statusForm.quoteAmount" :min="0" :precision="2" class="full" placeholder="报价" /><el-input v-model="statusForm.managerNote" type="textarea" placeholder="处理说明" /><el-button type="primary" @click="updateStatus">更新状态</el-button></section>
        <section class="timeline"><div class="section-title"><h3>交付里程碑</h3><el-button v-if="isAdmin" text @click="milestoneDialog=true">新增</el-button></div><article v-for="m in detail.milestones" :key="m.milestoneId"><i :class="{completed:m.status==='COMPLETED'}"></i><div><b>{{m.milestoneName}}</b><p>{{m.milestoneDescription||'暂无说明'}}</p><small>{{m.plannedDate||'未设日期'}} · {{milestoneNames[m.status]||m.status}}</small></div></article><el-empty v-if="!detail.milestones?.length" description="暂无里程碑" :image-size="60" /></section>
        <section class="work-orders"><div class="section-title"><h3>沟通与售后工单</h3><el-button text @click="workOrderDialog=true">发起工单</el-button></div><article v-for="w in detail.workOrders" :key="w.workOrderId"><div><b>{{w.subject}}</b><p>{{w.description}}</p><small>{{workOrderNames[w.status]||w.status}} · {{w.updateTime?.replace('T',' ')}}</small></div><el-button v-if="isAdmin&&w.status!=='CLOSED'" text @click="resolveWorkOrder(w)">处理</el-button></article><el-empty v-if="!detail.workOrders?.length" description="暂无工单" :image-size="60" /></section>
      </template>
    </el-drawer>

    <el-dialog v-model="milestoneDialog" title="新增交付里程碑" width="min(500px,92vw)"><el-form label-position="top"><el-form-item label="里程碑名称"><el-input v-model="milestoneForm.milestoneName" /></el-form-item><el-form-item label="说明"><el-input v-model="milestoneForm.milestoneDescription" type="textarea" /></el-form-item><el-form-item label="计划日期"><el-date-picker v-model="milestoneForm.plannedDate" value-format="YYYY-MM-DD" class="full" /></el-form-item></el-form><template #footer><el-button @click="milestoneDialog=false">取消</el-button><el-button type="primary" @click="createMilestone">保存</el-button></template></el-dialog>
    <el-dialog v-model="workOrderDialog" title="发起沟通工单" width="min(540px,92vw)"><el-form label-position="top"><el-form-item label="工单类型"><el-select v-model="workOrderForm.workOrderType" class="full"><el-option label="问题咨询" value="QUESTION"/><el-option label="缺陷反馈" value="BUG"/><el-option label="部署支持" value="DEPLOYMENT"/><el-option label="售后服务" value="AFTER_SALES"/></el-select></el-form-item><el-form-item label="主题"><el-input v-model="workOrderForm.subject" /></el-form-item><el-form-item label="详细说明"><el-input v-model="workOrderForm.description" type="textarea" :rows="4" /></el-form-item></el-form><template #footer><el-button @click="workOrderDialog=false">取消</el-button><el-button type="primary" @click="createWorkOrder">提交</el-button></template></el-dialog>
    <el-drawer v-model="publicDrawer" title="游客咨询处理" :size="drawerSize"><template v-if="publicDetail.inquiryId"><div class="detail-title"><span>{{publicDetail.inquiryNo}}</span><h2>{{publicDetail.contactName}}</h2><p>{{publicDetail.inquiryText}}</p></div><dl class="detail-meta"><div><dt>联系方式</dt><dd>{{publicDetail.contactValue}}</dd></div><div><dt>服务类型</dt><dd>{{typeNames[publicDetail.serviceType]}}</dd></div><div><dt>项目方向</dt><dd>{{publicDetail.projectType||'未填写'}}</dd></div><div><dt>当前状态</dt><dd>{{publicStatusNames[publicDetail.status]}}</dd></div></dl><div class="message-stream"><article v-for="m in publicDetail.messages" :key="m.messageId" :class="m.senderType.toLowerCase()"><b>{{m.senderType==='ADMIN'?'我的回复':'游客留言'}}</b><p>{{m.messageText}}</p><small>{{m.createTime}}</small></article></div><div v-if="publicDetail.status!=='CLOSED'" class="admin-action"><h3>回复游客</h3><el-input v-model="publicReply" type="textarea" :rows="4" maxlength="3000" /><div class="drawer-actions"><el-button type="primary" @click="replyPublicInquiry">发送回复</el-button><el-button @click="closePublicInquiry">结束咨询</el-button></div></div></template></el-drawer>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { publicInquiryAdminApi, serviceApi, reportError } from '../api'
const requests=ref([]),statusFilter=ref(''),requestDialog=ref(false),detailDrawer=ref(false),milestoneDialog=ref(false),workOrderDialog=ref(false),detail=ref({})
const publicInquiries=ref([]),publicDrawer=ref(false),publicDetail=ref({}),publicReply=ref('')
const user=JSON.parse(localStorage.getItem('userInfo')||'{}'),isAdmin=user.role==='ADMIN',drawerSize=computed(()=>innerWidth<720?'100%':'min(720px,74vw)')
const typeNames={DEVELOPMENT:'软件开发',GUIDANCE:'开发辅导',DEBUG:'调试排障',DEPLOYMENT:'部署上线',CONSULTING:'技术咨询'}
const statusNames={SUBMITTED:'已提交',ASSESSING:'评估中',QUOTED:'已报价',IN_PROGRESS:'进行中',DELIVERED:'已交付',CLOSED:'已关闭',CANCELLED:'已取消'}
const milestoneNames={PENDING:'待开始',IN_PROGRESS:'进行中',COMPLETED:'已完成',BLOCKED:'受阻'},workOrderNames={OPEN:'待处理',PROCESSING:'处理中',RESOLVED:'已解决',CLOSED:'已关闭'}
const publicStatusNames={NEW:'新咨询',CONTACTED:'沟通中',CLOSED:'已结束'}
const requestForm=reactive({serviceType:'DEVELOPMENT',title:'',requirementText:'',technologyStack:'',budgetRange:'',expectedDate:null,contactChannel:''})
const statusForm=reactive({status:'ASSESSING',quoteAmount:null,managerNote:''}),milestoneForm=reactive({milestoneName:'',milestoneDescription:'',plannedDate:null,status:'PENDING',sortNo:0}),workOrderForm=reactive({workOrderType:'QUESTION',subject:'',description:''})
const counts=computed(()=>({all:requests.value.length,progress:requests.value.filter(x=>['ASSESSING','QUOTED','IN_PROGRESS'].includes(x.status)).length,delivered:requests.value.filter(x=>['DELIVERED','CLOSED'].includes(x.status)).length}))
const load=async()=>{try{requests.value=(await serviceApi.requests(statusFilter.value)).data||[]}catch(e){reportError(e)}}
const createRequest=async()=>{if(!requestForm.title.trim()||!requestForm.requirementText.trim())return ElMessage.warning('请填写标题和需求说明');try{await serviceApi.createRequest(requestForm);requestDialog.value=false;requestForm.title='';requestForm.requirementText='';await load();ElMessage.success('需求已提交')}catch(e){reportError(e)}}
const openDetail=async id=>{try{detail.value=(await serviceApi.detail(id)).data||{};Object.assign(statusForm,{status:detail.value.request.status,quoteAmount:detail.value.request.quoteAmount,managerNote:detail.value.request.managerNote||''});detailDrawer.value=true}catch(e){reportError(e)}}
const refreshDetail=()=>openDetail(detail.value.request.requestId)
const updateStatus=async()=>{try{await serviceApi.updateStatus(detail.value.request.requestId,statusForm);await load();await refreshDetail();ElMessage.success('状态已更新')}catch(e){reportError(e)}}
const createMilestone=async()=>{if(!milestoneForm.milestoneName.trim())return ElMessage.warning('请输入里程碑名称');try{await serviceApi.createMilestone(detail.value.request.requestId,milestoneForm);milestoneDialog.value=false;milestoneForm.milestoneName='';await refreshDetail();ElMessage.success('里程碑已新增')}catch(e){reportError(e)}}
const createWorkOrder=async()=>{if(!workOrderForm.subject.trim()||!workOrderForm.description.trim())return ElMessage.warning('请填写工单主题和说明');try{await serviceApi.createWorkOrder({...workOrderForm,requestId:detail.value.request.requestId});workOrderDialog.value=false;workOrderForm.subject='';workOrderForm.description='';await refreshDetail();ElMessage.success('工单已提交')}catch(e){reportError(e)}}
const resolveWorkOrder=async order=>{try{const {value}=await ElMessageBox.prompt('填写处理结果','处理工单',{inputType:'textarea'});await serviceApi.updateWorkOrder(order.workOrderId,{status:'RESOLVED',resolutionText:value});await refreshDetail();ElMessage.success('工单已解决')}catch(e){if(e!=='cancel'&&e!=='close')reportError(e)}}
const loadPublicInquiries=async()=>{if(!isAdmin)return;try{publicInquiries.value=(await publicInquiryAdminApi.list()).data||[]}catch(e){reportError(e)}}
const openPublicInquiry=async id=>{try{publicDetail.value=(await publicInquiryAdminApi.detail(id)).data||{};publicDrawer.value=true}catch(e){reportError(e)}}
const replyPublicInquiry=async()=>{if(publicReply.value.trim().length<2)return ElMessage.warning('请填写回复内容');try{await publicInquiryAdminApi.reply(publicDetail.value.inquiryId,publicReply.value);publicReply.value='';await openPublicInquiry(publicDetail.value.inquiryId);await loadPublicInquiries();ElMessage.success('回复已保存，游客可用访问码查看')}catch(e){reportError(e)}}
const closePublicInquiry=async()=>{try{await publicInquiryAdminApi.updateStatus(publicDetail.value.inquiryId,'CLOSED');await openPublicInquiry(publicDetail.value.inquiryId);await loadPublicInquiries();ElMessage.success('咨询已结束')}catch(e){reportError(e)}}
onMounted(()=>{load();loadPublicInquiries()})
</script>
